import type { ExerciseCatalogEntry } from "./exercise-intake-contract";

export const SEEDED_EXERCISE_CATALOG: ExerciseCatalogEntry[] = [
  {
    name: "Squat",
    muscles: ["Quads", "Glutes"],
    category: "Lower",
    equipment: ["Bodyweight"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "RDL",
    muscles: ["Hamstrings", "Glutes"],
    category: "Lower",
    equipment: ["Barbell"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "SLDL",
    muscles: ["Hamstrings", "Glutes"],
    category: "Lower",
    equipment: ["Dumbbells"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Hip Thrust",
    muscles: ["Glutes"],
    category: "Lower",
    equipment: ["Barbell", "Bench"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Leg Press",
    muscles: ["Quads", "Glutes"],
    category: "Lower",
    equipment: ["Leg Press Machine"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Leg Curl",
    muscles: ["Hamstrings"],
    category: "Lower",
    equipment: ["Leg Curl Machine"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Bench Press",
    muscles: ["Chest", "Triceps"],
    category: "Upper Push",
    equipment: ["Barbell", "Bench"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Incline Press",
    muscles: ["Upper Chest", "Shoulders"],
    category: "Upper Push",
    equipment: ["Dumbbells", "Incline Bench"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Pull-Up / Lat Pulldown",
    muscles: ["Lats", "Biceps"],
    category: "Upper Pull",
    equipment: ["Pull-Up Bar"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Row",
    muscles: ["Upper Back", "Biceps"],
    category: "Upper Pull",
    equipment: ["Cable Machine"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Overhead Press",
    muscles: ["Shoulders", "Triceps"],
    category: "Upper Push",
    equipment: ["Dumbbells"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Bicep Curl",
    muscles: ["Biceps"],
    category: "Arms",
    equipment: ["Dumbbells"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Tricep Overhead",
    muscles: ["Triceps"],
    category: "Arms",
    equipment: ["Dumbbell"],
    defaultCameraAngle: "angled",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
  {
    name: "Lateral Raise",
    muscles: ["Side Delts"],
    category: "Shoulders",
    equipment: ["Dumbbells"],
    defaultCameraAngle: "angled",
    evidenceLevel: "insufficient",
    isAiGenerated: false,
  },
  {
    name: "RFESS",
    muscles: ["Quads", "Glutes"],
    category: "Lower",
    equipment: ["Dumbbells", "Bench"],
    defaultCameraAngle: "sagittal",
    evidenceLevel: "moderate",
    isAiGenerated: false,
  },
];
