export type ExerciseResearchEntry = {
  name: string;
  primaryJoints: string[];
  muscles: string[];
  movementPattern: string;
  biasSummary: string;
  evidenceLevel: "best-supported" | "likely superior" | "plausible bias" | "insufficient evidence";
  requiredEquipmentNames: string[];
  depthHeuristic: Record<string, unknown> | null;
  keyAngleChecks: Array<Record<string, unknown>>;
  researchChunks: Array<{
    source: string;
    sourceType: "paper_summary";
    exercises: string[];
    muscles: string[];
    text: string;
  }>;
};

export const EXERCISE_RESEARCH_CATALOG: ExerciseResearchEntry[] = [
  {
    name: "Bodyweight Squat",
    primaryJoints: ["knee", "hip", "ankle"],
    muscles: ["Quads", "Glutes", "Adductors"],
    movementPattern: "knee-dominant squat",
    biasSummary:
      "Depth is the strongest measurable proxy here: deeper squats tend to support more quad stimulus than shallow squats, while deeper bottom positions plausibly increase glute contribution. Bottom knee flexion plus hip depth and trunk-shin context matter more than ROM by itself.",
    evidenceLevel: "likely superior",
    requiredEquipmentNames: ["Bodyweight"],
    depthHeuristic: {
      metric: "bottom_knee_flexion_degrees",
      categories: {
        shallow: { min: 55, max: 70 },
        parallelApprox: { min: 85, max: 100 },
        deep: { min: 100, max: 125 },
      },
      note: "Loaded squat studies are the main basis, so use these as directionally useful bodyweight depth buckets rather than universal hard cutoffs.",
    },
    keyAngleChecks: [
      {
        joint: "knee",
        phase: "bottom",
        metric: "knee_flexion_degrees",
        optimalRange: { min: 95, max: 120 },
        acceptableRange: { min: 80, max: 125 },
        why: "Deeper squat training improved front-thigh hypertrophy and knee-extensor function more than shallow squat training.",
        evidenceSource: "Bloomquist et al. 2013, doi:10.1007/s00421-013-2642-7, PMID:23604798",
      },
      {
        joint: "hip",
        phase: "bottom",
        metric: "hip_depth_relative_to_knee",
        target: "hip crease at or slightly below knee when mobility and balance allow",
        why: "Greater depth plausibly increases gluteus maximus contribution within the squat pattern.",
        evidenceSource: "Caterisano et al. 2002, doi:10.1519/1533-4287(2002)016<0428:TEOBSD>2.0.CO;2, PMID:12173958",
      },
      {
        joint: "ankle",
        phase: "bottom",
        metric: "trunk_angle_relative_to_tibia",
        target: "allow forward knee travel and moderate torso lean instead of forcing a vertical shin",
        why: "Foot-position and dorsiflexion changes alter depth and the quad-versus-posterior loading context.",
        evidenceSource: "Bozkurt et al. 2025, doi:10.3389/fphys.2025.1727141, PMID:41574199",
      },
    ],
    researchChunks: [
      {
        source: "Bloomquist et al. 2013 - squat ROM and hypertrophy",
        sourceType: "paper_summary",
        exercises: ["Bodyweight Squat"],
        muscles: ["Quads", "Glutes"],
        text: "Title: Effect of range of motion in heavy load squatting on muscle and tendon adaptations. Year: 2013. DOI: 10.1007/s00421-013-2642-7. PMID: 23604798. Deep squats to about 120 degrees knee flexion produced greater front-thigh hypertrophy than shallow squats to about 60 degrees. Limitation: loaded barbell squats in young men, so the signal transfers directionally rather than exactly to bodyweight squats.",
      },
      {
        source: "Caterisano et al. 2002 - squat depth and glute EMG",
        sourceType: "paper_summary",
        exercises: ["Bodyweight Squat"],
        muscles: ["Glutes", "Quads"],
        text: "Title: The effect of back squat depth on the EMG activity of 4 superficial hip and thigh muscles. Year: 2002. DOI: 10.1519/1533-4287(2002)016<0428:TEOBSD>2.0.CO;2. PMID: 12173958. Gluteus maximus contribution increased from partial to parallel to full depth, supporting depth as a useful glute-bias proxy within squats. Limitation: EMG in loaded back squats, not a direct hypertrophy trial.",
      },
      {
        source: "Bozkurt et al. 2025 - foot position changes squat mechanics",
        sourceType: "paper_summary",
        exercises: ["Bodyweight Squat"],
        muscles: ["Quads", "Glutes"],
        text: "Title: Mechanobiological and neuromuscular responses to foot-position variations during front and back squat exercises. Year: 2025. DOI: 10.3389/fphys.2025.1727141. PMID: 41574199. Heel-elevated squats increased ankle dorsiflexion and squat depth and were associated with greater quadriceps activation than forefoot-elevated squats. Limitation: loaded front and back squats, not bodyweight-only squats.",
      },
    ],
  },
  {
    name: "RDL",
    primaryJoints: ["hip", "knee", "ankle"],
    muscles: ["Hamstrings", "Glutes", "Adductors"],
    movementPattern: "hip-dominant hinge",
    biasSummary:
      "RDL bias is best explained by long-length hamstring loading and high hip-extension demand, not ROM alone. A large hip hinge with a fairly fixed knee angle is more meaningful than chasing arbitrary depth.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Barbell"],
    depthHeuristic: null,
    keyAngleChecks: [
      {
        joint: "hip",
        phase: "eccentric",
        metric: "hip_flexion_degrees",
        target: "use a large hip hinge ROM until hamstring tension peaks without lumbar rounding",
        why: "The RDL produces very high hamstring force and stretch, so preserving true hip-hinge depth is central to its bias.",
        evidenceSource: "Breed et al. 2026, doi:10.1136/bjsports-2025-110847, PMID:41730607",
      },
      {
        joint: "knee",
        phase: "eccentric",
        metric: "knee_flexion_degrees",
        target: "soft knees with little additional bend after setup",
        why: "A relatively fixed knee angle keeps the pattern hip-dominant and lengthens the biarticular hamstrings more than a squat-like descent.",
        evidenceSource: "Crawford et al. 2025, doi:10.1249/MSS.0000000000003701, PMID:40085810",
      },
      {
        joint: "hip",
        phase: "eccentric",
        metric: "trunk_to_pelvis_alignment",
        target: "torso and pelvis move together as a hinge; avoid spinal flexion replacing hip motion",
        why: "The morphology data supporting the RDL assume a real hip hinge rather than extra spinal motion.",
        evidenceSource: "Crawford et al. 2025, doi:10.1249/MSS.0000000000003701, PMID:40085810",
      },
    ],
    researchChunks: [
      {
        source: "Crawford et al. 2025 - RDL vs Nordic morphology",
        sourceType: "paper_summary",
        exercises: ["RDL"],
        muscles: ["Hamstrings"],
        text: "Title: Hamstrings Muscle Architecture and Morphology Following 6 wk of an Eccentrically Biased Romanian Deadlift or Nordic Hamstring Exercise Intervention. Year: 2025. DOI: 10.1249/MSS.0000000000003701. PMID: 40085810. Six weeks of RDL or Nordic training similarly increased hamstring cross-sectional area and biceps femoris fascicle length, supporting the RDL as a meaningful hamstring-growth option. Limitation: short intervention and not a broad exercise comparison.",
      },
      {
        source: "Breed et al. 2026 - hamstring force and stretch across exercises",
        sourceType: "paper_summary",
        exercises: ["RDL"],
        muscles: ["Hamstrings"],
        text: "Title: Hamstring force and stretch during progressively increasing running speeds and the eccentric phase of resistance training exercises commonly used for injury prevention and rehabilitation. Year: 2026. DOI: 10.1136/bjsports-2025-110847. PMID: 41730607. The bilateral RDL produced the highest biceps femoris long head and semimembranosus peak force and among the greatest stretch demands of the tested exercises. Limitation: biomechanics and modeling work, not a hypertrophy trial.",
      },
      {
        source: "Maeo et al. 2021 - long muscle lengths favor hamstring growth",
        sourceType: "paper_summary",
        exercises: ["RDL"],
        muscles: ["Hamstrings"],
        text: "Title: Greater Hamstrings Muscle Hypertrophy but Similar Damage Protection after Training at Long versus Short Muscle Lengths. Year: 2021. DOI: 10.1249/MSS.0000000000002523. PMID: 33009197. Seated leg curl training at longer hamstring lengths outperformed prone leg curl for whole-hamstring hypertrophy, reinforcing the long-length principle that likely supports RDL use. Limitation: not an RDL study, so it supports mechanism more than exact exercise ranking.",
      },
    ],
  },
  {
    name: "SLDL",
    primaryJoints: ["hip", "knee", "ankle"],
    muscles: ["Hamstrings", "Glutes", "Glute Medius"],
    movementPattern: "unilateral hip-dominant hinge",
    biasSummary:
      "Direct hypertrophy evidence is very limited. The strongest app-relevant signal is control quality: stance-hip hinge depth, pelvic control, and trunk stability determine whether the movement behaves like a hamstring-glute hinge or mostly a balance drill.",
    evidenceLevel: "insufficient evidence",
    requiredEquipmentNames: ["Dumbbell"],
    depthHeuristic: null,
    keyAngleChecks: [
      {
        joint: "hip",
        phase: "eccentric",
        metric: "hip_flexion_degrees",
        target: "reach by hinging on the stance hip rather than rounding the spine",
        why: "A true unilateral hinge is more likely to preserve posterior-chain loading than a shallow balance-only reach.",
        evidenceSource: "Jeong and Park 2025, doi:10.3390/sports13080242, PMID:40863751",
      },
      {
        joint: "hip",
        phase: "bottom",
        metric: "pelvic_rotation_or_drop_degrees",
        target: "keep pelvis mostly square with only small drift",
        why: "Large pelvic drift turns the task into balance recovery and reduces measurement usefulness.",
        evidenceSource: "Marin et al. 2026, PMCID:PMC12952505; Jeong and Park 2025, PMID:40863751",
      },
      {
        joint: "trunk",
        phase: "bottom",
        metric: "trunk_sidebend_or_rotation_degrees",
        target: "minimal side-bend and trunk rotation over the stance leg",
        why: "SLDL quality is strongly tied to stability and neuromuscular control, which makes trunk drift a practical pose-derived quality marker.",
        evidenceSource: "Marin et al. 2026, PMCID:PMC12952505",
      },
      {
        joint: "knee",
        phase: "eccentric",
        metric: "knee_flexion_degrees",
        target: "soft stance knee that stays fairly constant through the rep",
        why: "Too much rebending turns the movement away from a hinge and makes rep-to-rep loading less comparable.",
        evidenceSource: "Jeong and Park 2025, doi:10.3390/sports13080242, PMID:40863751",
      },
    ],
    researchChunks: [
      {
        source: "Jeong and Park 2025 - SLDL stability and muscle activation",
        sourceType: "paper_summary",
        exercises: ["SLDL"],
        muscles: ["Glute Medius", "Hamstrings", "Calves"],
        text: "Title: Comparison of Lower Limb COP and Muscle Activation During Single-Leg Deadlift Using Elastic and Inelastic Barbells. Year: 2025. DOI: 10.3390/sports13080242. PMID: 40863751. SLDL performance changed with balance demand and speed, and higher-demand conditions increased gluteus medius and hamstring activation, highlighting stability and pelvic control as key measurable fields. Limitation: acute EMG and COP study, not hypertrophy research.",
      },
      {
        source: "Marin et al. 2026 - smartphone SLDL stability",
        sourceType: "paper_summary",
        exercises: ["SLDL"],
        muscles: ["Glutes", "Hamstrings"],
        text: "Title: Smartphone-Assessed Single-Leg Deadlift Stability is Associated with Sprint Velocity in Youth Soccer Players. Year: 2026. PMCID: PMC12952505. Partial-range single-leg deadlift stability was associated with sprint performance, supporting trunk and pelvic control as meaningful field metrics. Limitation: performance association study, not a hypertrophy or exercise-comparison trial.",
      },
      {
        source: "Otani et al. 2025 - single-leg RDL in hamstring prevention",
        sourceType: "paper_summary",
        exercises: ["SLDL"],
        muscles: ["Hamstrings", "Glutes"],
        text: "Title: The Effect of Single Leg Romanian Deadlift on the Risk of Hamstring Strain Injuries in Track and Field Athletes: A Cohort Study. Year: 2025. DOI: 10.26603/001c.136803. PMID: 40322523. Adding single-leg RDLs to warm-up reduced mild-to-moderate hamstring strain risk, supporting the movement as a controllable posterior-chain drill. Limitation: injury-prevention cohort, not a hypertrophy study.",
      },
    ],
  },
  {
    name: "Hip Thrust",
    primaryJoints: ["hip", "knee"],
    muscles: ["Glutes", "Hamstrings", "Adductors"],
    movementPattern: "horizontal hip extension",
    biasSummary:
      "Hip thrust is a glute-focused hip-extension exercise, but direct evidence does not show clear glute hypertrophy superiority over squats. The strongest signal is a shorter-muscle-length, lockout-heavy resistance profile, so top hip extension quality matters more than total ROM.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Barbell", "Bench"],
    depthHeuristic: null,
    keyAngleChecks: [
      {
        joint: "hip",
        phase: "top",
        metric: "hip_extension_degrees",
        target: "finish near neutral hip extension without turning the rep into lumbar hyperextension",
        why: "The exercise is defined by completing horizontal hip extension; failing to reach a clean top position changes the intended glute-loading profile.",
        evidenceSource: "Plotkin et al. 2023, doi:10.3389/fphys.2023.1279170, PMID:37877099",
      },
      {
        joint: "knee",
        phase: "top",
        metric: "knee_flexion_degrees",
        target: "keep a consistent mid-range knee bend across reps as a setup proxy",
        why: "Hip thrust outcomes are sensitive to setup consistency, and the exercise provides relatively low hamstring stretch compared with long-length hinges like the RDL.",
        evidenceSource: "Breed et al. 2026, doi:10.1136/bjsports-2025-110847, PMID:41730607",
      },
      {
        joint: "trunk",
        phase: "top",
        metric: "ribcage_pelvis_alignment",
        target: "stack ribcage over pelvis at lockout",
        why: "This helps distinguish true hip extension from compensatory spinal extension when scoring end-range quality.",
        evidenceSource: "Plotkin et al. 2023, doi:10.3389/fphys.2023.1279170, PMID:37877099",
      },
    ],
    researchChunks: [
      {
        source: "Plotkin et al. 2023 - hip thrust vs squat hypertrophy",
        sourceType: "paper_summary",
        exercises: ["Hip Thrust"],
        muscles: ["Glutes", "Quads", "Adductors"],
        text: "Title: Hip thrust and back squat training elicit similar gluteus muscle hypertrophy and transfer similarly to the deadlift. Year: 2023. DOI: 10.3389/fphys.2023.1279170. PMID: 37877099. Nine weeks of hip thrust and squat training produced similar glute hypertrophy, while squats increased quadriceps and adductor size more. Limitation: untrained participants and a relatively short intervention.",
      },
      {
        source: "Krause Neto et al. 2025 - glute hypertrophy systematic review",
        sourceType: "paper_summary",
        exercises: ["Hip Thrust"],
        muscles: ["Glutes"],
        text: "Title: The impact of resistance training on gluteus maximus hypertrophy: a systematic review and meta-analysis. Year: 2025. DOI: 10.3389/fphys.2025.1542334. PMID: 40276368. Resistance training had a moderate effect on gluteus maximus hypertrophy overall, and the review suggested hip thrusts are reasonable to prioritize when glute emphasis is the goal. Limitation: exercise-specific conclusions rely on a limited underlying evidence base.",
      },
      {
        source: "Breed et al. 2026 - hip thrust as lower-stretch hip extension",
        sourceType: "paper_summary",
        exercises: ["Hip Thrust"],
        muscles: ["Glutes", "Hamstrings"],
        text: "Title: Hamstring force and stretch during progressively increasing running speeds and the eccentric phase of resistance training exercises commonly used for injury prevention and rehabilitation. Year: 2026. DOI: 10.1136/bjsports-2025-110847. PMID: 41730607. Compared with the RDL, the hip thrust imposed much lower hamstring stretch, supporting the idea that it is a shorter-length hip-extension pattern. Limitation: biomechanics study focused on hamstring mechanics, not direct glute hypertrophy.",
      },
    ],
  },
  {
    name: "Leg Press",
    primaryJoints: ["knee", "hip", "ankle"],
    muscles: ["Quads", "Glutes", "Adductors"],
    movementPattern: "machine knee-dominant press",
    biasSummary:
      "Leg press is a strong quad-focused option, but recent direct evidence suggests moderate versus individualized deep knee ROM can produce similar quad hypertrophy in trained lifters. Repeatable depth plus bottom hip-knee context matters more than assuming deeper is always better.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Leg Press Machine"],
    depthHeuristic: {
      metric: "bottom_knee_flexion_degrees",
      categories: {
        restrictedRepeatable: "about 100 degrees knee flexion",
        fullIndividualized: "individual maximum, often greater than 100 degrees",
      },
      note: "Current direct evidence supports tracking depth mainly for repeatability and individual response, not as a universal deeper-is-better rule for quads.",
    },
    keyAngleChecks: [
      {
        joint: "knee",
        phase: "bottom",
        metric: "knee_flexion_degrees",
        target: "use a repeatable individualized ROM instead of assuming deepest possible always wins",
        why: "Recent direct evidence found similar quadriceps hypertrophy between about 5 to 100 degrees and individualized full ROM over 8 weeks.",
        evidenceSource: "Larsen et al. 2025, doi:10.1080/02640414.2025.2481534, PMID:40113586",
      },
      {
        joint: "hip",
        phase: "bottom",
        metric: "hip_flexion_degrees",
        target: "deeper bottom positions likely increase glute contribution, but score this as a context field rather than a universal target",
        why: "Glute hypertrophy reviews suggest leg press can grow glute max, which likely depends partly on bottom-position leverage and joint angles.",
        evidenceSource: "Krause Neto et al. 2025, doi:10.3389/fphys.2025.1542334, PMID:40276368",
      },
      {
        joint: "trunk",
        phase: "bottom",
        metric: "pelvic_roll_under_visible",
        target: "stop before visible posterior pelvic roll-under if the camera view allows it",
        why: "This makes bottom depth more repeatable and reduces mixing pelvic motion with intended hip and knee ROM.",
        evidenceSource: "Larsen et al. 2025, doi:10.1080/02640414.2025.2481534, PMID:40113586",
      },
    ],
    researchChunks: [
      {
        source: "Larsen et al. 2025 - leg press ROM and quad hypertrophy",
        sourceType: "paper_summary",
        exercises: ["Leg Press"],
        muscles: ["Quads"],
        text: "Title: Knee flexion range of motion does not influence muscle hypertrophy of the quadriceps femoris during leg press training in resistance-trained individuals. Year: 2025. DOI: 10.1080/02640414.2025.2481534. PMID: 40113586. In trained participants, about 5 to 100 degrees and individualized maximal ROM produced similar quadriceps hypertrophy over 8 weeks. Limitation: short study duration and outcomes focused on quadriceps, not glute or adductor changes.",
      },
      {
        source: "Krause Neto et al. 2025 - glute meta includes leg press",
        sourceType: "paper_summary",
        exercises: ["Leg Press"],
        muscles: ["Glutes", "Quads"],
        text: "Title: The impact of resistance training on gluteus maximus hypertrophy: a systematic review and meta-analysis. Year: 2025. DOI: 10.3389/fphys.2025.1542334. PMID: 40276368. The review concluded that leg press can contribute to gluteus maximus hypertrophy, supporting storage of hip-depth context instead of treating leg press as quad-only. Limitation: the exercise-specific glute conclusion is based on a limited number of studies.",
      },
    ],
  },
  {
    name: "Leg Curl",
    primaryJoints: ["knee", "hip"],
    muscles: ["Hamstrings"],
    movementPattern: "knee flexion isolation",
    biasSummary:
      "This is the clearest lower-body case where direct hypertrophy evidence supports a setup difference: hip-flexed seated leg curls outperform prone leg curls for whole-hamstring and biarticular hamstring growth. Hip angle and lengthened-start exposure matter more than ROM alone.",
    evidenceLevel: "best-supported",
    requiredEquipmentNames: ["Leg Curl Machine"],
    depthHeuristic: null,
    keyAngleChecks: [
      {
        joint: "hip",
        phase: "setup",
        metric: "hip_flexion_degrees",
        target: "hip-flexed seated setup when the goal is biarticular hamstring hypertrophy",
        why: "Longer hamstring operating lengths in seated curls produced greater hypertrophy than prone curls.",
        evidenceSource: "Maeo et al. 2021, doi:10.1249/MSS.0000000000002523, PMID:33009197",
      },
      {
        joint: "knee",
        phase: "eccentric",
        metric: "knee_flexion_degrees",
        acceptableRange: { min: 0, max: 90 },
        why: "The key direct study used about 0 to 90 degrees knee ROM in both conditions, making full available knee-flexion ROM a practical storeable field.",
        evidenceSource: "Maeo et al. 2021, doi:10.1249/MSS.0000000000002523, PMID:33009197",
      },
      {
        joint: "knee",
        phase: "lengthened_start",
        metric: "lengthened_position_exposure",
        target: "do not cut off the more extended-knee start position if the goal is growth",
        why: "The long-length condition appears to be a major driver of the seated curl advantage.",
        evidenceSource: "Maeo et al. 2021, doi:10.1249/MSS.0000000000002523, PMID:33009197",
      },
    ],
    researchChunks: [
      {
        source: "Maeo et al. 2021 - seated vs prone leg curl",
        sourceType: "paper_summary",
        exercises: ["Leg Curl"],
        muscles: ["Hamstrings"],
        text: "Title: Greater Hamstrings Muscle Hypertrophy but Similar Damage Protection after Training at Long versus Short Muscle Lengths. Year: 2021. DOI: 10.1249/MSS.0000000000002523. PMID: 33009197. Seated leg curls produced greater whole-hamstring hypertrophy than prone leg curls, especially in the biarticular hamstrings, supporting hip angle as a first-class metadata field. Limitation: compares seated and prone machine curls, not all curl variants.",
      },
      {
        source: "Maeo et al. 2021 - operating length note",
        sourceType: "paper_summary",
        exercises: ["Leg Curl"],
        muscles: ["Hamstrings"],
        text: "Title: Greater Hamstrings Muscle Hypertrophy but Similar Damage Protection after Training at Long versus Short Muscle Lengths. Year: 2021. DOI: 10.1249/MSS.0000000000002523. PMID: 33009197. The seated condition used a 90-degree hip angle and placed the biarticular hamstrings at longer operating lengths across the same 0 to 90 degree knee ROM. Limitation: muscle-length inference is model-based within the trial.",
      },
    ],
  },
  {
    name: "RFESS",
    primaryJoints: ["knee", "hip", "ankle"],
    muscles: ["Quads", "Glutes", "Adductors"],
    movementPattern: "unilateral knee-dominant split squat",
    biasSummary:
      "Direct hypertrophy evidence for RFESS-specific bias is limited, but biomechanics support clear coaching-relevant context: torso angle, knee travel, and stance width change whether the front leg behaves more knee-dominant or more hip-extensor dominant. Those are useful bias fields rather than hard superiority claims.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Bench", "Dumbbell"],
    depthHeuristic: {
      metric: "front_leg_bottom_depth",
      categories: {
        kneeDominant: "front knee travels forward with a more upright torso",
        hipBiased: "more forward torso lean with less forward knee travel",
      },
      note: "These are bias categories from biomechanics and EMG, not direct hypertrophy cutoffs.",
    },
    keyAngleChecks: [
      {
        joint: "trunk",
        phase: "descent",
        metric: "trunk_angle_relative_to_floor",
        target: "more forward torso lean for posterior-chain bias; more upright torso for a more knee-dominant pattern",
        why: "Forward trunk flexion increased gluteus maximus and biceps femoris activation in Bulgarian split squat variations.",
        evidenceSource: "Aygun-Polat et al. 2025, doi:10.1186/s13102-025-01306-z, PMID:40867012",
      },
      {
        joint: "knee",
        phase: "bottom",
        metric: "front_knee_forward_travel_or_shin_angle",
        target: "allow more forward knee travel for quad bias; restrict it somewhat for more hip bias",
        why: "Front-leg mechanics shift with torso and stance choices, so shin angle is a practical proxy for front-leg demand distribution.",
        evidenceSource: "Aygun-Polat et al. 2025, doi:10.1186/s13102-025-01306-z, PMID:40867012",
      },
      {
        joint: "hip",
        phase: "bottom",
        metric: "stance_width",
        target: "track narrow versus wide stance because it changes front-hip extensor loading",
        why: "Rear-leg derived moment substantially contributes to front-hip extensor resistance, and the contribution changes with stance width and trunk angle.",
        evidenceSource: "Arakawa et al. 2025, doi:10.70252/NEXQ5666, PMID:40909869",
      },
    ],
    researchChunks: [
      {
        source: "Aygun-Polat et al. 2025 - trunk position in Bulgarian split squat",
        sourceType: "paper_summary",
        exercises: ["RFESS"],
        muscles: ["Quads", "Glutes", "Hamstrings"],
        text: "Title: Targeted muscle activation in Bulgarian split squat variations: effects of trunk position and suspension-based execution. Year: 2025. DOI: 10.1186/s13102-025-01306-z. PMID: 40867012. Forward trunk flexion increased gluteus maximus, biceps femoris, and rectus femoris activation, making torso angle a strong app-relevant bias field. Limitation: acute EMG study in trained female athletes, not a hypertrophy trial.",
      },
      {
        source: "Arakawa et al. 2025 - rear-leg moment in Bulgarian split squat",
        sourceType: "paper_summary",
        exercises: ["RFESS"],
        muscles: ["Glutes", "Quads"],
        text: "Title: Rear Leg-derived Moment Contributes to Resistance Against Hip Extension in Bulgarian Split Squats. Year: 2025. DOI: 10.70252/NEXQ5666. PMID: 40909869. Rear-leg derived moment accounted for a large share of total front-hip extensor resistance and changed with stance width and trunk lean, supporting stance and torso metrics in the app. Limitation: bodyweight biomechanics study with a small sample, not direct hypertrophy evidence.",
      },
    ],
  },
  {
    name: "Bench Press",
    primaryJoints: ["shoulder", "elbow"],
    muscles: ["Pectoralis Major", "Anterior Deltoid", "Triceps Brachii"],
    movementPattern: "horizontal press",
    biasSummary:
      "Treat this as the default horizontal chest press for overall pec plus triceps loading. Claims about specific chest-region hypertrophy versus incline are still mostly indirect; touch point, grip width, elbow flare, and ROM change leverage and resistance profile more than ROM alone.",
    evidenceLevel: "likely superior",
    requiredEquipmentNames: ["Barbell", "Bench"],
    depthHeuristic: {
      metric: "bottom_elbow_flexion_and_touch_point",
      note: "Store whether reps reach a clear bottom with substantial elbow flexion and a lower-to-mid sternum touch proxy versus shortened top-half partials.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "setup",
        metric: "bench_angle_degrees",
        optimalRange: { min: 0, max: 15 },
        acceptableRange: { min: 0, max: 30 },
        why: "Horizontal or near-horizontal pressing is the main whole-pec benchmark; steeper inclines shift demand toward anterior deltoid and away from lower pec.",
        evidenceSource: "Lauver et al. 2015, doi:10.1080/17461391.2015.1022605, PMID:25799093",
      },
      {
        joint: "elbow",
        phase: "bottom",
        metric: "elbow_flexion_category",
        target: "full-ROM bottom with obvious elbow flexion rather than shortened partials when hypertrophy is the goal",
        why: "Long-muscle-length loading appears more relevant than total ROM by itself.",
        evidenceSource: "Wolf et al. 2023, doi:10.47206/ijsc.v3i1.182",
      },
      {
        joint: "shoulder",
        phase: "bottom",
        metric: "bar_touch_height_proxy",
        target: "lower-to-mid sternum touch zone; a much higher touch point usually increases shoulder flexion and anterior-delt bias",
        why: "Touch point materially changes pressing leverage and bar path.",
        evidenceSource: "Larsen et al. 2021, doi:10.3389/fspor.2020.637066",
      },
      {
        joint: "elbow",
        phase: "midrange",
        metric: "forearm_verticality_proxy",
        target: "wrist stacked near elbow from the front view; extreme tuck or flare changes moment arms and bar path",
        why: "This is a practical proxy for leverage consistency rather than a folklore elbow-angle rule.",
        evidenceSource: "Larsen et al. 2021, doi:10.3389/fspor.2020.637066",
      },
    ],
    researchChunks: [
      {
        source: "Lauver et al. 2015 - bench angle and activation",
        sourceType: "paper_summary",
        exercises: ["Bench Press"],
        muscles: ["Pectoralis Major", "Anterior Deltoid", "Triceps Brachii"],
        text: "Title: Influence of bench angle on upper extremity muscular activation during bench press exercise. Year: 2015. DOI: 10.1080/17461391.2015.1022605. PMID: 25799093. Horizontal bench produced strong overall pec activation, while 30 to 45 degree inclines increased upper-pec activation at some phases and reduced lower-pec contribution. Limitation: acute EMG study, not a longitudinal hypertrophy trial.",
      },
      {
        source: "Wolf et al. 2023 - partial vs full ROM review",
        sourceType: "paper_summary",
        exercises: ["Bench Press"],
        muscles: ["Pectoralis Major", "Triceps Brachii"],
        text: "Title: Partial vs full range of motion resistance training: a systematic review and meta-analysis. Year: 2023. DOI: 10.47206/ijsc.v3i1.182. Across resistance training studies, full ROM is not automatically superior; long-muscle-length partials can match or outperform full ROM in some contexts. Limitation: not bench-press specific and not enough to set one universal ROM rule for chest pressing.",
      },
      {
        source: "Larsen et al. 2021 - grip width and bench mechanics",
        sourceType: "paper_summary",
        exercises: ["Bench Press"],
        muscles: ["Pectoralis Major", "Anterior Deltoid", "Triceps Brachii"],
        text: "Title: A biomechanical analysis of wide, medium, and narrow grip width effects on kinematics, horizontal kinetics, and muscle activity on the sticking region in recreationally trained males during 1-RM bench pressing. Year: 2021. DOI: 10.3389/fspor.2020.637066. Grip width materially changes ROM, bar path, horizontal kinetics, and sticking-region mechanics, so leverage context should be stored alongside joint angles. Limitation: 1RM biomechanics, not a hypertrophy comparison.",
      },
    ],
  },
  {
    name: "Incline Press",
    primaryJoints: ["shoulder", "elbow"],
    muscles: ["Clavicular Pectoralis Major", "Anterior Deltoid", "Triceps Brachii"],
    movementPattern: "inclined press",
    biasSummary:
      "Low-incline pressing likely biases clavicular pec and anterior deltoid more than flat pressing, but direct hypertrophy evidence is limited. As bench angle rises, the lift increasingly behaves like a shoulder press, so angle selection matters more than calling any incline upper chest.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Incline Bench", "Dumbbell"],
    depthHeuristic: {
      metric: "bench_angle_degrees",
      lowIncline: { min: 15, max: 30 },
      highIncline: { min: 31, max: 45 },
      note: "Low incline is the main practical upper-chest-bias category; steeper inclines shift more toward anterior deltoid.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "setup",
        metric: "bench_angle_degrees",
        optimalRange: { min: 15, max: 30 },
        acceptableRange: { min: 15, max: 45 },
        why: "Lower inclines appear to preserve pec contribution while nudging bias toward the clavicular region; steeper inclines become more shoulder-dominant.",
        evidenceSource: "Lauver et al. 2015, doi:10.1080/17461391.2015.1022605, PMID:25799093",
      },
      {
        joint: "shoulder",
        phase: "bottom",
        metric: "touch_point_proxy",
        target: "upper chest or clavicle-line touch zone; if touch drifts too low the movement resembles flat bench more than incline press",
        why: "Touch point changes the line of press and shoulder moment-arm context.",
        evidenceSource: "Trebs et al. 2010, doi:10.1519/JSC.0b013e3181ddfae7",
      },
      {
        joint: "shoulder",
        phase: "bottom",
        metric: "humerus_to_torso_angle_category",
        target: "moderate flare; very steep incline plus high flare likely shifts bias further toward anterior deltoid",
        why: "Humeral path is a more useful leverages field than a single generic ROM score.",
        evidenceSource: "Lauver et al. 2015, doi:10.1080/17461391.2015.1022605, PMID:25799093",
      },
    ],
    researchChunks: [
      {
        source: "Lauver et al. 2015 - incline angle and activation",
        sourceType: "paper_summary",
        exercises: ["Incline Press"],
        muscles: ["Clavicular Pectoralis Major", "Anterior Deltoid"],
        text: "Title: Influence of bench angle on upper extremity muscular activation during bench press exercise. Year: 2015. DOI: 10.1080/17461391.2015.1022605. PMID: 25799093. Thirty- and 45-degree inclines increased upper-pec activation during part of the concentric phase, while 45 degrees reduced lower-pec activation versus horizontal pressing. Limitation: phase-specific EMG differences do not prove superior clavicular-pec hypertrophy.",
      },
      {
        source: "Trebs et al. 2010 - chest press at several angles",
        sourceType: "paper_summary",
        exercises: ["Incline Press"],
        muscles: ["Clavicular Pectoralis Major", "Anterior Deltoid"],
        text: "Title: An Electromyography Analysis of 3 Muscles Surrounding the Shoulder Joint During the Performance of a Chest Press Exercise at Several Angles. Year: 2010. DOI: 10.1519/JSC.0b013e3181ddfae7. Changing press angle altered activation of clavicular pec, sternocostal pec, and anterior deltoid, supporting angle-based categories instead of treating all incline setups as equivalent. Limitation: acute EMG in a chest-press context, not a direct hypertrophy trial on incline barbell pressing.",
      },
    ],
  },
  {
    name: "Overhead Press",
    primaryJoints: ["shoulder", "elbow"],
    muscles: ["Anterior Deltoid", "Medial Deltoid", "Triceps Brachii", "Upper Trapezius"],
    movementPattern: "vertical press",
    biasSummary:
      "A vertical press plausibly biases anterior and medial deltoid plus triceps, but direct evidence that it is hypertrophy-superior to other shoulder exercises is limited. Humeral path and fuller elbow ROM matter more than ROM alone.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Barbell"],
    depthHeuristic: {
      metric: "bottom_elbow_flexion_and_humeral_plane",
      note: "Store whether reps start near upper chest or clavicle with elbows slightly forward of the torso versus shortened top-half partials or straight-out lateral flare.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "midrange",
        metric: "humeral_plane_category",
        target: "scapular-plane or slight-forward elbow path instead of straight lateral flare",
        why: "Moment arms across the glenohumeral joint change with humeral angle, making humeral path a useful leverage field.",
        evidenceSource: "Hik et al. 2019, doi:10.1111/joa.12903",
      },
      {
        joint: "elbow",
        phase: "bottom",
        metric: "elbow_flexion_category",
        target: "use full available ROM from upper chest or clavicle when tolerated; shortened ROM reduces overall shoulder-muscle activation",
        why: "The direct EMG work supports recording whether the rep actually uses the lengthened start.",
        evidenceSource: "Paoli et al. 2010, doi:10.1519/JSC.0b013e3181d756ea, PMID:20508462",
      },
      {
        joint: "elbow",
        phase: "top",
        metric: "elbow_extension_degrees",
        optimalRange: { min: 165, max: 180 },
        acceptableRange: { min: 150, max: 180 },
        why: "Near-full top position helps standardize ROM and vertical stack instead of turning the rep into a shortened partial.",
        evidenceSource: "Paoli et al. 2010, doi:10.1519/JSC.0b013e3181d756ea, PMID:20508462",
      },
    ],
    researchChunks: [
      {
        source: "Paoli et al. 2010 - ROM in military press",
        sourceType: "paper_summary",
        exercises: ["Overhead Press"],
        muscles: ["Anterior Deltoid", "Medial Deltoid", "Upper Trapezius"],
        text: "Title: Influence of different ranges of motion on selective recruitment of shoulder muscles in the sitting military press: an electromyographic study. Year: 2010. DOI: 10.1519/JSC.0b013e3181d756ea. PMID: 20508462. Wider ROM increased activation of most measured shoulder muscles; with heavy loads, an intermediate ROM could reduce trapezius involvement without reducing medial deltoid activation. Limitation: small acute EMG study in a seated military press, not a long-term hypertrophy comparison.",
      },
      {
        source: "Hik et al. 2019 - glenohumeral moment-arm review",
        sourceType: "paper_summary",
        exercises: ["Overhead Press"],
        muscles: ["Anterior Deltoid", "Medial Deltoid"],
        text: "Title: The moment arms of the muscles spanning the glenohumeral joint: A systematic review. Year: 2019. DOI: 10.1111/joa.12903. Glenohumeral muscle moment arms change with humeral angle, supporting storage of humeral-plane and elevation context rather than ROM alone. Limitation: anatomical and biomechanical review, not an exercise trial.",
      },
    ],
  },
  {
    name: "Tricep Overhead",
    primaryJoints: ["shoulder", "elbow"],
    muscles: ["Triceps Brachii Long Head", "Triceps Brachii Lateral Head", "Triceps Brachii Medial Head"],
    movementPattern: "overhead elbow extension",
    biasSummary:
      "This is one of the better-supported ways to bias the triceps long head because the overhead shoulder position lengthens it across the shoulder joint. Arm position plus deep elbow flexion matter more than generic ROM totals.",
    evidenceLevel: "likely superior",
    requiredEquipmentNames: ["Dumbbell"],
    depthHeuristic: {
      metric: "shoulder_position_category",
      note: "Primary category is overhead or near-overhead upper arm versus neutral or by-side upper arm, then bottom elbow-flexion depth.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "setup",
        metric: "shoulder_position_category",
        target: "overhead or near-overhead upper arm, not neutral by side",
        why: "Overhead positioning lengthens the long head and produced substantially greater long-head hypertrophy than neutral-arm training.",
        evidenceSource: "Maeo et al. 2023, doi:10.1080/17461391.2022.2100279, PMID:35819335",
      },
      {
        joint: "elbow",
        phase: "bottom",
        metric: "elbow_flexion_category",
        target: "deep elbow flexion stretch rather than shortened top-half partials",
        why: "This preserves the long-length exposure that likely underpins the long-head advantage.",
        evidenceSource: "Maeo et al. 2023, doi:10.1080/17461391.2022.2100279, PMID:35819335",
      },
      {
        joint: "shoulder",
        phase: "throughout",
        metric: "upper_arm_drift_proxy",
        target: "keep upper arm mostly fixed overhead; excessive shoulder swing changes the exercise and load sharing",
        why: "Upper-arm drift turns the rep into a different movement pattern and muddies the long-head interpretation.",
        evidenceSource: "Stasinaki et al. 2018, doi:10.3390/jfmk3020028",
      },
    ],
    researchChunks: [
      {
        source: "Maeo et al. 2023 - overhead vs neutral triceps training",
        sourceType: "paper_summary",
        exercises: ["Tricep Overhead"],
        muscles: ["Triceps Brachii Long Head"],
        text: "Title: Triceps brachii hypertrophy is substantially greater after elbow extension training performed in the overhead versus neutral arm position. Year: 2023. DOI: 10.1080/17461391.2022.2100279. PMID: 35819335. Training elbow extensions in an overhead arm position produced substantially greater long-head triceps hypertrophy than neutral-arm training. Limitation: directly supports long-head bias, but not every overhead-extension variation.",
      },
      {
        source: "Stasinaki et al. 2018 - triceps fascicle length context",
        sourceType: "paper_summary",
        exercises: ["Tricep Overhead"],
        muscles: ["Triceps Brachii"],
        text: "Title: Triceps Brachii Muscle Strength and Architectural Adaptations with Resistance Training Exercises at Short or Long Fascicle Length. Year: 2018. DOI: 10.3390/jfmk3020028. Early training at short or long fascicle length improved triceps size similarly, showing the long-length advantage was not settled before newer direct long-head work. Limitation: small novice sample and weaker than the later direct overhead-versus-neutral hypertrophy study.",
      },
    ],
  },
  {
    name: "Lateral Raise",
    primaryJoints: ["shoulder", "elbow"],
    muscles: ["Medial Deltoid", "Anterior Deltoid", "Upper Trapezius", "Supraspinatus"],
    movementPattern: "shoulder abduction raise",
    biasSummary:
      "Lateral raises clearly target the deltoid, especially the lateral region, but strong claims that one plane, implement, or rotation is definitively best for hypertrophy are still limited. Peak humeral elevation, scapular-plane path, and stable elbow bend are the best practical fields.",
    evidenceLevel: "insufficient evidence",
    requiredEquipmentNames: ["Dumbbell"],
    depthHeuristic: {
      metric: "peak_humeral_abduction_degrees",
      shoulderHeight: { min: 80, max: 100 },
      belowShoulder: { min: 40, max: 79 },
      aboveShoulder: { min: 101, max: 130 },
      note: "Shoulder-height peak is the most practical pose-derived category; evidence that going much higher is better for hypertrophy is weak.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "peak",
        metric: "humeral_abduction_degrees",
        optimalRange: { min: 80, max: 100 },
        acceptableRange: { min: 60, max: 120 },
        why: "Shoulder-height elevation is the clearest practical target; higher ranges may raise trap contribution without clear proof of better hypertrophy.",
        evidenceSource: "Coratella et al. 2020, doi:10.3390/ijerph17176015",
      },
      {
        joint: "shoulder",
        phase: "throughout",
        metric: "humeral_plane_category",
        target: "slight forward or scapular-plane raise instead of straight frontal-plane or behind-body drift",
        why: "Changing the plane of abduction alters recruitment patterns, so plane is more informative than bare ROM.",
        evidenceSource: "Reed et al. 2016, doi:10.1016/j.math.2015.04.014, PMID:25920341",
      },
      {
        joint: "shoulder",
        phase: "throughout",
        metric: "humeral_rotation_proxy",
        target: "neutral or slight external rotation; internal-rotation pouring cues are not well supported as superior",
        why: "Rotation changes recruitment patterns and may raise upper-trap involvement without proving better deltoid growth.",
        evidenceSource: "Coratella et al. 2020, doi:10.3390/ijerph17176015",
      },
      {
        joint: "elbow",
        phase: "throughout",
        metric: "elbow_bend_consistency",
        target: "keep a small stable bend; changing elbow bend changes the lever arm independent of shoulder ROM",
        why: "Elbow bend changes the effective loading even when the shoulder motion looks similar.",
        evidenceSource: "Hik et al. 2019, doi:10.1111/joa.12903",
      },
    ],
    researchChunks: [
      {
        source: "Pinto et al. 2025 - dumbbell vs cable lateral raise",
        sourceType: "paper_summary",
        exercises: ["Lateral Raise"],
        muscles: ["Medial Deltoid"],
        text: "Title: Dumbbell versus cable lateral raises for lateral deltoid hypertrophy: an experimental study. Year: 2025. DOI: 10.3389/fphys.2025.1611468. When ROM was standardized and matched, dumbbell and cable lateral raises produced similar lateral-deltoid hypertrophy in trained lifters. Limitation: addresses implement choice, not optimal plane, rotation, or peak elevation height.",
      },
      {
        source: "Coratella et al. 2020 - lateral raise variations",
        sourceType: "paper_summary",
        exercises: ["Lateral Raise"],
        muscles: ["Medial Deltoid", "Upper Trapezius"],
        text: "Title: An Electromyographic Analysis of Lateral Raise Variations and Frontal Raise in Competitive Bodybuilders. Year: 2020. DOI: 10.3390/ijerph17176015. Neutral lateral raises favored medial deltoid more than some other variants, while internal rotation increased posterior deltoid, upper trapezius, and triceps activity. Limitation: acute EMG cannot by itself establish long-term hypertrophy superiority.",
      },
      {
        source: "Reed et al. 2016 - plane of abduction and recruitment",
        sourceType: "paper_summary",
        exercises: ["Lateral Raise"],
        muscles: ["Medial Deltoid", "Supraspinatus"],
        text: "Title: Does changing the plane of abduction influence shoulder muscle recruitment patterns in healthy individuals? Year: 2016. DOI: 10.1016/j.math.2015.04.014. PMID: 25920341. Changing the plane of shoulder abduction alters recruitment patterns, supporting a scapular-plane category as a useful app field. Limitation: healthy-subject recruitment study, not a resistance-training hypertrophy trial.",
      },
    ],
  },
  {
    name: "Pull-Up",
    primaryJoints: ["shoulder", "elbow", "scapulothoracic"],
    muscles: ["Latissimus Dorsi", "Teres Major", "Biceps Brachii", "Brachialis", "Mid/Lower Trapezius"],
    movementPattern: "vertical pull",
    biasSummary:
      "Treat this as a bodyweight vertical pull where lat stimulus depends more on a true overhead stretch and then driving shoulder adduction or extension with substantial elbow flexion than on grip folklore. Swing control and elbow path matter because they change the resistance profile.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Pull-Up Bar"],
    depthHeuristic: {
      metric: "overhead_start_to_top_finish_quality",
      note: "Store dead-hang or overhead start, top finish category, and a separate swing-control category instead of pretending there is one magic ROM score.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "bottom",
        metric: "overhead_start_quality",
        target: "classify as full overhead hang versus partial hang using upper-arm-to-torso angle and elbow extension at the bottom",
        why: "Long-length loading is more relevant than ROM alone; the stimulus is likely better when the lats and biceps actually start from a lengthened overhead position.",
        evidenceSource: "Kassiano et al. 2026, doi:10.1055/a-2733-7605",
      },
      {
        joint: "elbow",
        phase: "top",
        metric: "top_elbow_flexion_finish",
        target: "classify finish as chin-to-bar or full, partial-high, or partial-mid",
        why: "This is a practical shortening proxy without inventing weak numeric thresholds.",
        evidenceSource: "Kassiano et al. 2026, doi:10.1055/a-2733-7605",
      },
      {
        joint: "trunk",
        phase: "throughout",
        metric: "torso_swing_or_lean",
        target: "vertical or slight lean versus large swing or kip",
        why: "Body English materially changes the resistance profile and makes hypertrophy coaching less exercise-specific.",
        evidenceSource: "Sakamoto et al. 2025, doi:10.1002/ejsc.12243",
      },
      {
        joint: "elbow",
        phase: "midrange",
        metric: "elbow_path_relative_to_torso",
        target: "tucked or scapular-plane versus flared",
        why: "Elbow path changes whether the movement behaves more like shoulder adduction and extension for lats versus more upper-back and posterior-delt involvement.",
        evidenceSource: "Marcolin et al. 2025, doi:10.3390/jfmk10030345",
      },
    ],
    researchChunks: [
      {
        source: "Kassiano et al. 2026 - muscle length and exercise selection review",
        sourceType: "paper_summary",
        exercises: ["Pull-Up"],
        muscles: ["Latissimus Dorsi", "Biceps Brachii"],
        text: "Title: The interplay between muscle length, range of motion, and exercise selection: a review. Year: 2026. DOI: 10.1055/a-2733-7605. Across direct and indirect literature, hypertrophy tends to favor exercises and ROMs that load muscles at longer lengths when external torque is meaningful there. Limitation: review-level and not pull-up specific.",
      },
      {
        source: "Sakamoto et al. 2025 - lat pulldown transfer to pull-up performance",
        sourceType: "paper_summary",
        exercises: ["Pull-Up"],
        muscles: ["Latissimus Dorsi", "Biceps Brachii"],
        text: "Title: Eight-week lat pull-down resistance training with joint instability leads to superior pull-up endurance performance and reduced antagonist coactivation in recreationally active male college students. Year: 2025. DOI: 10.1002/ejsc.12243. Lat-pulldown training improved pull-up performance, supporting broad vertical-pull transfer and similar prime-mover demands. Limitation: performance study, not hypertrophy.",
      },
      {
        source: "Marcolin et al. 2025 - pulldown grip variations",
        sourceType: "paper_summary",
        exercises: ["Pull-Up"],
        muscles: ["Latissimus Dorsi", "Posterior Deltoid"],
        text: "Title: Electromyographic Analysis of Back Muscle Activation During Lat Pulldown Exercise: Effects of Grip Variations and Forearm Orientation. Year: 2025. DOI: 10.3390/jfmk10030345. Grip width and orientation changes did not meaningfully alter latissimus dorsi activation across pulldown variants. Limitation: acute EMG on pulldowns, not direct pull-up hypertrophy.",
      },
    ],
  },
  {
    name: "Lat Pulldown",
    primaryJoints: ["shoulder", "elbow", "scapulothoracic"],
    muscles: ["Latissimus Dorsi", "Teres Major", "Biceps Brachii", "Brachialis", "Posterior Deltoid", "Mid/Lower Trapezius"],
    movementPattern: "vertical pull",
    biasSummary:
      "The literature does not strongly support major lat differences from common grip variations, so the most useful stored fields are torso lean, start stretch, elbow path, and whether the bar comes in front of the face or chest versus behind the neck. Exact grip-width superiority is not well supported.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Lat Pulldown Machine"],
    depthHeuristic: {
      metric: "overhead_start_to_finish_path",
      note: "Store overhead stretch, finish landmark, and front-of-body versus behind-neck path separately.",
    },
    keyAngleChecks: [
      {
        joint: "trunk",
        phase: "throughout",
        metric: "torso_lean_category",
        target: "upright or slight lean versus pronounced layback",
        why: "Large layback changes the exercise toward a hybrid row and alters moment-arm context more than grip tweaks likely do.",
        evidenceSource: "Marcolin et al. 2025, doi:10.3390/jfmk10030345",
      },
      {
        joint: "shoulder",
        phase: "descent",
        metric: "bar_path_proxy",
        target: "front-of-face or upper-chest versus behind-neck using wrist and elbow position relative to the head and shoulders",
        why: "Front versus back pulldown changes joint position and excitation pattern; front is the more practical default.",
        evidenceSource: "Sartorio et al. 2024, doi:10.5114/jhk/185211",
      },
      {
        joint: "shoulder",
        phase: "top",
        metric: "overhead_start_quality",
        target: "full overhead stretch versus shortened start",
        why: "This is more relevant to likely hypertrophy stimulus than small grip changes when torque remains on the target tissues.",
        evidenceSource: "Kassiano et al. 2026, doi:10.1055/a-2733-7605",
      },
      {
        joint: "elbow",
        phase: "midrange",
        metric: "elbow_path_relative_to_torso",
        target: "tucked or scapular-plane versus flared",
        why: "A useful pose proxy for whether the rep behaves more like shoulder extension and adduction for lats versus more upper-back and posterior-delt contribution.",
        evidenceSource: "Marcolin et al. 2025, doi:10.3390/jfmk10030345",
      },
    ],
    researchChunks: [
      {
        source: "Marcolin et al. 2025 - pulldown grip variations",
        sourceType: "paper_summary",
        exercises: ["Lat Pulldown"],
        muscles: ["Latissimus Dorsi", "Posterior Deltoid"],
        text: "Title: Electromyographic Analysis of Back Muscle Activation During Lat Pulldown Exercise: Effects of Grip Variations and Forearm Orientation. Year: 2025. DOI: 10.3390/jfmk10030345. Across seven pulldown variants, latissimus dorsi EMG was not significantly different; only some posterior-deltoid differences emerged. Limitation: acute EMG, experienced men only, not hypertrophy.",
      },
      {
        source: "Sartorio et al. 2024 - front vs back lat pulldown excitation",
        sourceType: "paper_summary",
        exercises: ["Lat Pulldown"],
        muscles: ["Latissimus Dorsi", "Posterior Deltoid"],
        text: "Title: High-Density Electromyography Excitation in Front vs. Back Lat Pull-Down Prime Movers. Year: 2024. DOI: 10.5114/jhk/185211. Front pulldowns showed greater overall prime-mover excitation in key phases, while back pulldowns changed spatial excitation patterns. Limitation: acute EMG and not a long-term growth study.",
      },
      {
        source: "Kassiano et al. 2026 - muscle length and exercise selection review",
        sourceType: "paper_summary",
        exercises: ["Lat Pulldown"],
        muscles: ["Latissimus Dorsi", "Biceps Brachii"],
        text: "Title: The interplay between muscle length, range of motion, and exercise selection: a review. Year: 2026. DOI: 10.1055/a-2733-7605. Exercise selection seems more favorable when meaningful torque exists at longer muscle lengths, supporting full overhead starts if load stays on the target tissues. Limitation: general review, not pulldown-specific.",
      },
    ],
  },
  {
    name: "Row",
    primaryJoints: ["shoulder", "elbow", "scapulothoracic"],
    muscles: ["Latissimus Dorsi", "Teres Major", "Mid Trapezius", "Rhomboids", "Posterior Deltoid", "Biceps Brachii"],
    movementPattern: "horizontal pull",
    biasSummary:
      "Rows are best stored as a family of horizontal pulls where torso angle and elbow path likely matter more than cueing. Tucked elbows and lower-rib or hip-directed finishes plausibly bias shoulder extension and lats, while more abducted elbows and upper-rib finishes plausibly bias mid-back and posterior deltoid.",
    evidenceLevel: "plausible bias",
    requiredEquipmentNames: ["Cable Row Machine"],
    depthHeuristic: {
      metric: "reach_start_and_finish_landmark",
      note: "Store stretched or reached start separately from finish landmark so the app can infer both lengthened loading and line of pull.",
    },
    keyAngleChecks: [
      {
        joint: "trunk",
        phase: "setup",
        metric: "torso_angle_category",
        target: "more upright or chest-supported versus moderate hinge versus pronounced hinge",
        why: "Torso angle changes the line of pull and whether the rep behaves more like shoulder extension for lats or upper-back retraction work.",
        evidenceSource: "Muyor et al. 2025, doi:10.1177/19417381251393643",
      },
      {
        joint: "elbow",
        phase: "midrange",
        metric: "elbow_path_relative_to_torso",
        target: "tucked, midline, or flared",
        why: "Probably the most useful pose-derived proxy for lat-biased versus upper-back or posterior-delt-biased rowing.",
        evidenceSource: "Leong et al. 2025, doi:10.3390/jfmk11010006",
      },
      {
        joint: "elbow",
        phase: "finish",
        metric: "finish_landmark",
        target: "elbows or wrists finishing near lower ribs, mid ribs, or upper chest",
        why: "This gives an app-storable endpoint proxy for resistance profile and muscle bias without pretending exact degrees are validated.",
        evidenceSource: "Leong et al. 2025, doi:10.3390/jfmk11010006",
      },
      {
        joint: "scapula",
        phase: "start",
        metric: "start_reach_vs_fixed_scapula",
        target: "reached or protracted start versus fixed or retracted start",
        why: "Scapular freedom changes distribution of excitation more than overall excitation, so it is worth storing as a category.",
        evidenceSource: "Leong et al. 2025, doi:10.3390/jfmk11010006",
      },
    ],
    researchChunks: [
      {
        source: "Leong et al. 2025 - seated row and scapular positions",
        sourceType: "paper_summary",
        exercises: ["Row"],
        muscles: ["Latissimus Dorsi", "Mid Trapezius"],
        text: "Title: High-Density Surface Electromyography Excitation of Prime Movers Across Scapular Positions in the Seated Row. Year: 2025. DOI: 10.3390/jfmk11010006. Fixed- and free-scapula seated rows produced broadly similar excitation, with some eccentric increases for latissimus dorsi and middle trapezius in the fixed condition. Limitation: acute EMG in one seated-row setup, not hypertrophy.",
      },
      {
        source: "Muyor et al. 2025 - regional lat activation",
        sourceType: "paper_summary",
        exercises: ["Row"],
        muscles: ["Latissimus Dorsi"],
        text: "Title: Regional Activation of the Latissimus Dorsi Muscle by High-Density Surface Electromyography During Isometric Shoulder and Trunk Exercises. Year: 2025. DOI: 10.1177/19417381251393643. Shoulder extension preferentially recruited the thoracic latissimus region more than adduction or trunk tasks. Limitation: isometric lab study, not a dynamic row or growth study.",
      },
      {
        source: "Andersen et al. 2004 - traditional pulling exercise EMG",
        sourceType: "paper_summary",
        exercises: ["Row"],
        muscles: ["Latissimus Dorsi", "Mid Trapezius", "Rhomboids"],
        text: "Title: Variations in muscle activation levels during traditional latissimus dorsi weight training exercises: An experimental study. Year: 2004. DOI: 10.1186/1476-5918-3-4. Seated rows produced high latissimus dorsi to biceps activation ratios and the highest middle trapezius and rhomboid activity among compared pulling tasks. Limitation: older acute EMG and isometric work.",
      },
    ],
  },
  {
    name: "Bicep Curl",
    primaryJoints: ["elbow", "shoulder"],
    muscles: ["Biceps Brachii", "Brachialis", "Brachioradialis"],
    movementPattern: "elbow flexion isolation",
    biasSummary:
      "For hypertrophy, the strongest current takeaway is that loaded elbow flexion through a meaningful lengthened range matters more than simply calling one shoulder position best. The app should prioritize bottom-position elbow extension, shoulder-position category, and upper-arm drift rather than overclaiming preacher versus Bayesian superiority.",
    evidenceLevel: "likely superior",
    requiredEquipmentNames: ["Dumbbell"],
    depthHeuristic: {
      metric: "lengthened_bottom_exposure_plus_finish_quality",
      note: "Do not treat full ROM as sufficient without noting where torque is highest and whether the rep actually uses the bottom range.",
    },
    keyAngleChecks: [
      {
        joint: "shoulder",
        phase: "setup",
        metric: "shoulder_position_category",
        target: "extended behind torso, neutral at side, or flexed in front",
        why: "This is the most practical pose-derived proxy for long-head length context, but current direct hypertrophy evidence does not show a clear winner when resistance profiles are matched.",
        evidenceSource: "Nunes et al. 2025, doi:10.1002/ejsc.12279",
      },
      {
        joint: "elbow",
        phase: "bottom",
        metric: "bottom_elbow_angle",
        target: "near-full extension or moderate-flexion start instead of skipping the bottom range",
        why: "This is a useful proxy for lengthened loading exposure, which appears more important than shoulder position alone.",
        evidenceSource: "Pereira et al. 2025, doi:10.1002/ejsc.70087",
      },
      {
        joint: "elbow",
        phase: "top",
        metric: "top_elbow_flexion_finish",
        target: "full, moderate, or short finish",
        why: "Lets the app distinguish true loaded shortening from shortened partials.",
        evidenceSource: "Pereira et al. 2025, doi:10.1002/ejsc.70087",
      },
      {
        joint: "shoulder",
        phase: "throughout",
        metric: "upper_arm_drift",
        target: "stable humerus versus shoulder-flexion cheat during the concentric",
        why: "Shoulder drift changes the exercise mechanics and can offload the intended elbow-flexor pattern.",
        evidenceSource: "Pohl et al. 2025, doi:10.3390/muscles4040045",
      },
    ],
    researchChunks: [
      {
        source: "Nunes et al. 2025 - preacher vs Bayesian curls",
        sourceType: "paper_summary",
        exercises: ["Bicep Curl"],
        muscles: ["Biceps Brachii", "Brachialis"],
        text: "Title: Comparison Between Shoulder Flexed and Extended Positions in Elbow Flexion Resistance Training on Regional Hypertrophy and Maximum Strength: Preacher versus Bayesian Cable Curls. Year: 2025. DOI: 10.1002/ejsc.12279. Preacher and Bayesian cable curls produced similar elbow-flexor hypertrophy and strength when resistance profiles were matched. Limitation: small sample and only two specific curl setups.",
      },
      {
        source: "Pereira et al. 2025 - long-length partial preacher curls",
        sourceType: "paper_summary",
        exercises: ["Bicep Curl"],
        muscles: ["Biceps Brachii", "Brachialis"],
        text: "Title: Partial Range, Full Gains? The Effect of 8 Weeks of Partial Range of Motion Training at Long Muscle Lengths on Elbow Flexor Hypertrophy and Strength in Trained Individuals. Year: 2025. DOI: 10.1002/ejsc.70087. Long-length partial preacher curls showed modest regional hypertrophy advantages, suggesting bottom-range loading may matter. Limitation: short study with small sample and modest effect sizes.",
      },
      {
        source: "Pohl et al. 2025 - dumbbell vs Bayesian curl EMG",
        sourceType: "paper_summary",
        exercises: ["Bicep Curl"],
        muscles: ["Biceps Brachii"],
        text: "Title: An Exploratory Study of Biceps Brachii Electromyographic Activity During Traditional Dumbbell Versus Bayesian Cable Curls. Year: 2025. DOI: 10.3390/muscles4040045. Traditional dumbbell curls showed higher acute biceps EMG than Bayesian cable curls. Limitation: acute EMG conflicts with longer-term hypertrophy equivalence and should not be overinterpreted.",
      },
    ],
  },
];
